# Target Keywords Configuration for POCT Group Ecosystem
# Broad, generic product-category terms for GeM tender tracking.
# No brand/model names used — only clinical/product-level terminology.

import re

_RAW_KEYWORDS = {
    "Q-Line": [
        # --- Q-Line: Analyzers & Instruments ---
        "Hematology analyzer",
        "3 Part Hematology Analyzer",
        "5 Part Hematology Analyzer",
        "Hemoglobin Analyzer",
        "HbA1c HPLC",
        "HPLC System",
        "High Performance Liquid Chromatography",
        "Coagulation analyzer",
        "ESR analyzer",
        "Erythrocyte Sedimentation Rate Analyzer",
        "Biochemistry analyzer",
        "Semi-Auto Biochemistry Analyzer",
        "Automated Clinical Chemistry Analyzer",
        "Fully Auto Chemistry Analyzer",
        "Electrolyte analyzer",
        "Urine analyzer",
        "Automated Urine Analyzer",
        "Immunoassay analyzer",
        "Fluorescence immunoassay analyzer",
        "Chemiluminescence immunoassay analyzer",
        "Hormone analyzer",
        "Thyroid analyzer",
        "Fertility analyzer",
        "Bilirubinometer",
        "Microbiological safety cabinet",
        "Biological Safety Cabinet",
        "Laminar flow cabinet",
        "Real time PCR system",
        "RT-PCR system",
        "Real time PCR machine",
        "Automated PCR",
        "Gene Xpert",
        "Tuberculosis diagnostic",
        "CB-NAAT",
        "TrueNat",
        "Centrifuge",
        "Refrigerated centrifuge",
        "Clinical chemistry reagents",
        "ELISA reader",
        "ELISA washer",
        "Microplate reader",
        "Rapid test kits",
        # --- Q-Line: Rapid Test Kits ---
        "HIV 1/2 Antibody Rapid Test Kit",
        "HIV Ag/Ab 4th Gen Rapid Test Kit",
        "HBsAg Rapid Test Kit",
        "HCV Antibody Rapid Test Kit",
        "Syphilis Antibody Rapid Test Kit",
        "Dengue NS1 Rapid Test Kit",
        "Dengue Combo Rapid Test Kit",
        "Malaria Rapid Test Kit",
        "Pregnancy Rapid Test Kit",
        "HIV Syphilis Duo Rapid Test Kit",
        "Typhoid Rapid Test Kit",
        "Leptospira Rapid Test Kit",
        "Scrub Typhus Rapid Test Kit",
        "CHIKUNGUNYA Rapid Test Kit",
        "Troponin Rapid Test Kit",
        "D-Dimer Rapid Test Kit",
        "Ferritin Rapid Test Kit",
        "CRP Rapid Test Kit",
        "POC Hemoglobin analyzer",
        "Nucleic acid extraction system",
        "Automated nucleic acid extraction system",
        "Viral Transport Medium",
        "COVID-19 RT-PCR Kit",
        "Molecular diagnostic kits",
        "Viral collection and transport medium",
        # --- Biochemistry Reagents (Full Auto & Semi Auto) ---
        "Biochemistry reagents",
        "Diagnostics testing reagents",
        "ALAT GPT Diagnostics testing reagents",
        "Albumin Diagnostics testing reagents",
        "Alkaline Phosphatase Diagnostics testing reagents",
        "Amylase Diagnostics testing reagents",
        "ASAT GOT Diagnostics testing reagents",
        "Bilirubin Direct Diagnostics testing reagents",
        "Bilirubin Total Diagnostics testing reagents",
        "Bio Cal Diagnostics testing reagents",
        "Bio Norm Diagnostics testing reagents",
        "Bio Path Diagnostics testing reagents",
        "Calcium Diagnostics testing reagents",
        "Cholesterol Diagnostics testing reagents",
        "Creatinine Diagnostics testing reagents",
        "CRP Diagnostics testing reagents",
        "g-Glutamyl Transferase Diagnostics testing reagents",
        "Glucose Diagnostics testing reagents",
        "HDL Cholesterol Direct Diagnostics testing reagents",
        "Lactate Dehydrogenase LDH Diagnostics testing reagents",
        "Micro Albumin Diagnostics testing reagents",
        "Total Protein Diagnostics testing reagents",
        "Triglyceride Diagnostics testing reagents",
        "Urea Diagnostics testing reagents",
        "Uric Acid Diagnostics testing reagents",
        "Cleanser for Biochemistry Fully Auto Analyser",
        "RA Factor Diagnostics testing reagents",
        "Serum Iron Fully Automated Biochemistry",
        "TIBC Fully Automated Biochemistry Analyzer",
        "Erba Wash Diagnostics testing reagents",
        "SGOT Diagnostics testing reagents",
        "SGPT Diagnostics testing reagents",
        "HDL Diagnostics testing reagents Semi Auto",
        # --- HPLC Reagents ---
        "553 Lyphochek HbA2F BI LEVEL Kit HPLC",
        "740 Lypochek diabetic control",
        "Dual Kits HPLC HbA1c Diagnostics testing reagents",
        "H Clean Diagnostics testing reagents",
        "HPLC reagents",
        "HbA1c HPLC reagents",
        # --- Hematology / 5-Part Cell Counter Reagents ---
        "H560 DIL Diagnostics testing reagents 5-Part Cell Counter",
        "H560 Lyse 1 Diagnostics testing reagents 5-Part Cell Counter",
        "H560 Lyse 2 Diagnostics testing reagents 5-Part Cell Counter",
        "Trilevel Control Diagnostics testing reagents",
        "5-Part Cell Counter reagents",
        "Hematology reagents",
        # --- Coagulation Reagents ---
        "Activated Prothrombin Time FSR",
        "Prothrombin Time FSR Diagnostics testing reagents",
        "Coagulation reagents",
        "Coagulometer reagents",
        # --- Electrolyte Reagents ---
        "Electrolyte reagents",
        "DEPROTINISER ISE Kit Electrolyte Analyser",
        "IFS Solution Kit Electrolyte Analyser",
        "ISE reagents Electrolyte",
        # --- Microbiology / Bacterial ID ---
        "GN Test ID card Bacterial Identification System",
        "GP Test ID card Bacterial Identification System",
        "YST Test ID card Bacterial Identification System",
        "NH Test ID card Bacterial Identification System",
        "3D FA Plus BACT ALERT Blood Culture",
        "3D FN Plus BACT ALERT Blood Culture",
        "3D PF Plus BACT ALERT Blood Culture",
        "AST N235 AST Card Bacterial Identification System",
        "AST N405 AST Card Bacterial Identification System",
        "AST N406 AST Card Bacterial Identification System",
        "AST N407 AST Card Bacterial Identification System",
        "AST P628 AST Card Bacterial Identification System",
        "AST ST03 AST Card Bacterial Identification System",
        "AST YS08 AST Card Bacterial Identification System",
        "Bacterial Identification System",
        "Automated Bacterial Identification",
        "Blood Culture System",
        "BACT ALERT Blood Culture",
    ],
    "Heidelco": [
        # --- Heidelco: Ventilators ---
        "Ventilator",
        "ICU Ventilator",
        "Portable Ventilator",
        "Transport Ventilator",
        "NICU Ventilator",
        "Neonatal Ventilator",
        "High Frequency Oscillatory Ventilator",
        "Non-Invasive Ventilator",
        "BiPAP",
        "CPAP",
        "BPAP",
        # --- Heidelco: Anesthesia ---
        "Defibrillator",
        "Anesthesia machine",
        "Anaesthesia machine",
        "Anesthesia Workstation",
        "Anaesthetic Vaporiser",
        "Anesthesia Ventilator",
        # --- Heidelco: Patient Monitoring ---
        "Patient monitor",
        "Multipara Monitor",
        "Multi parameter patient monitor",
        "Bedside monitor",
        "Telemetry monitor",
        "Central monitoring system",
        "Fetal monitor",
        "Foetal Doppler",
        "ECG machine",
        "12 Lead ECG",
        "Cardiac marker analyzer",
        "Critical care equipment",
        "Pulse Oximeter finger tip",
        "SpO2 monitor",
        # --- Heidelco: Respiratory Therapy Accessories ---
        "Nasal mask",
        "Full face mask",
        "Patient circuit",
        "Breathing circuit",
        "Testlung",
        "Silicone anesthesia mask",
        "Anaesthesia mask",
        "Catheter mount",
        "Rebreathing bag",
        "HME filter",
        "Heat Moisture Exchanger",
        "Mapleson circuit",
        "Adult brain circuit",
        "Jackson Rees circuit",
        "Magill circuit",
        "Bain circuit",
        "Water trap",
        "CO2 absorber",
        "Soda lime",
        # --- Heidelco: Oxygen Therapy ---
        "Oxygen mask",
        "Venturi mask",
        "Jet nebulizer set",
        "Nebulizer mask kit",
        "Nasal cannula",
        "High Flow Nasal Cannula",
        "HFNC",
        "Oxygen therapy accessories",
        "Non-Rebreathing mask",
        # --- Heidelco: Infusion / Pumps ---
        "Syringe pump",
        "Infusion pump",
        "Volumetric infusion pump",
        "Peristaltic pump",
        # --- Heidelco: Other ICU / OT ---
        "Suction machine",
        "Phototherapy unit",
        "Neonatal incubator",
        "Radiant warmer",
        "Examination light",
        "Operating light",
        "Surgical light",
    ],
    "POCT": [
        # --- POCT: Turnkey / Lab Setup Services ---
        "Turnkey laboratory",
        "Telemedicine services",
        "Telemedicine unit",
        "Teleconsultation",
        "ICU management services",
        "Health screening services",
        "AI health kiosk",
        "Health ATM",
        "Diagnostic kiosk",
        "Medical equipment supply",
        "Diagnostic laboratory instruments",
        "Comprehensive lab setup",
        "Laboratory infrastructure",
        "Lab on wheels",
        "Mobile health unit",
        # --- POCT: Point-of-Care Devices ---
        "Pulse Oximeter",
        "Digital BP Apparatus",
        "Glucometer",
        "Blood glucose monitor",
        "HbA1c analyzer point of care",
        "Nebulizer",
        "Oxygen Concentrator",
        "Infrared Thermometer",
        "Digital thermometer",
        "Weighing scale medical",
        "BMI machine",
        "Urinalysis strip reader",
        "Urine dipstick reader",
        "Hemoglobin meter",
        "Hand held glucometer",
        # --- POCT: Cold Chain & Storage ---
        "Walk in Cooler",
        "Walk-in Cold Room",
        "Vaccine refrigerator",
        "ILR refrigerator",
        "Ice Lined Refrigerator",
        "Deep freezer",
        "Ultra low temperature freezer",
        "Cold box",
        "Vaccine carrier",
        "Refrigerator 2-8 degree",
        # --- POCT: Air Quality ---
        "Air Purifier",
        "Indoor Air Purifier",
        "Portable Air Purifier",
        "HEPA Air Purifier",
    ],
    "iQline": [
        # --- iQline: Core Software Products ---
        "Laboratory Information Management System",
        "LIMS",
        "Hospital Information Management System",
        "HIMS",
        "Radiology Information Management System",
        "RIMS",
        "PACS",
        "Picture Archiving and Communication System",
        "Medical University Management System",
        "MUMS",
        "E-Prescription software",
        "Electronic prescription",
        "Enterprise Resource Planning",
        "ERP hospital",
        "Early Warning System",
        "Bid Management System",
        # --- iQline: Healthcare IT broader categories ---
        "Hospital Management Software",
        "Hospital Management System",
        "Health Management Information System",
        "Electronic Health Record",
        "EHR software",
        "EMR software",
        "Electronic Medical Record",
        "Telemedicine software",
        "Patient management software",
        "Pharmacy management software",
        "Inventory management hospital",
        "OPD management software",
        "IPD management software",
        "Queue management system hospital",
        "Billing software hospital",
        "Nursing management software",
        "ICU monitoring software",
        "ABDM compliant software",
        "Ayushman Bharat Digital Mission software",
        "RIS PACS radiology",
        "DICOM viewer",
        "Teleradiology",
        "Lab automation software",
        "Barcode tracking laboratory",
    ],
}

# Clean any lingering citation artifacts automatically
def _clean(keyword):
    return re.sub(r":contentReference\[.*?\]\{.*?\}", "", keyword).strip()

TARGET_KEYWORDS = {
    brand: [_clean(kw) for kw in kws]
    for brand, kws in _RAW_KEYWORDS.items()
}
